//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace screen_capture.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CAPTURE_SELECTION_MOD {
            get {
                return ((int)(this["CAPTURE_SELECTION_MOD"]));
            }
            set {
                this["CAPTURE_SELECTION_MOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81")]
        public int CAPTURE_SELECTION_KEY {
            get {
                return ((int)(this["CAPTURE_SELECTION_KEY"]));
            }
            set {
                this["CAPTURE_SELECTION_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CAPTURE_SELECTION_TEXT {
            get {
                return ((string)(this["CAPTURE_SELECTION_TEXT"]));
            }
            set {
                this["CAPTURE_SELECTION_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMG_PATH {
            get {
                return ((string)(this["IMG_PATH"]));
            }
            set {
                this["IMG_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMG_NAMING {
            get {
                return ((string)(this["IMG_NAMING"]));
            }
            set {
                this["IMG_NAMING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GIF_PATH {
            get {
                return ((string)(this["GIF_PATH"]));
            }
            set {
                this["GIF_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GIF_NAMING {
            get {
                return ((string)(this["GIF_NAMING"]));
            }
            set {
                this["GIF_NAMING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CAPTURE_ALL_MOD {
            get {
                return ((int)(this["CAPTURE_ALL_MOD"]));
            }
            set {
                this["CAPTURE_ALL_MOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public int CAPTURE_ALL_KEY {
            get {
                return ((int)(this["CAPTURE_ALL_KEY"]));
            }
            set {
                this["CAPTURE_ALL_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+W")]
        public string CAPTURE_ALL_TEXT {
            get {
                return ((string)(this["CAPTURE_ALL_TEXT"]));
            }
            set {
                this["CAPTURE_ALL_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysTop {
            get {
                return ((bool)(this["AlwaysTop"]));
            }
            set {
                this["AlwaysTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Sync {
            get {
                return ((bool)(this["Sync"]));
            }
            set {
                this["Sync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int IMG_NUM_RECT {
            get {
                return ((int)(this["IMG_NUM_RECT"]));
            }
            set {
                this["IMG_NUM_RECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GIF_NUM_RECT {
            get {
                return ((int)(this["GIF_NUM_RECT"]));
            }
            set {
                this["GIF_NUM_RECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IMG_AUTOSAVE {
            get {
                return ((bool)(this["IMG_AUTOSAVE"]));
            }
            set {
                this["IMG_AUTOSAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IMG_FORMAT {
            get {
                return ((int)(this["IMG_FORMAT"]));
            }
            set {
                this["IMG_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GIF_AUTOSAVE {
            get {
                return ((bool)(this["GIF_AUTOSAVE"]));
            }
            set {
                this["GIF_AUTOSAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GIF_QUALITY {
            get {
                return ((int)(this["GIF_QUALITY"]));
            }
            set {
                this["GIF_QUALITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IMG_SELECTION {
            get {
                return ((bool)(this["IMG_SELECTION"]));
            }
            set {
                this["IMG_SELECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IMG_ALL {
            get {
                return ((bool)(this["IMG_ALL"]));
            }
            set {
                this["IMG_ALL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GIF_SELECTION {
            get {
                return ((bool)(this["GIF_SELECTION"]));
            }
            set {
                this["GIF_SELECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GIF_ALL {
            get {
                return ((bool)(this["GIF_ALL"]));
            }
            set {
                this["GIF_ALL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RECORD_SELECTION_MOD {
            get {
                return ((int)(this["RECORD_SELECTION_MOD"]));
            }
            set {
                this["RECORD_SELECTION_MOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81")]
        public int RECORD_SELECTION_KEY {
            get {
                return ((int)(this["RECORD_SELECTION_KEY"]));
            }
            set {
                this["RECORD_SELECTION_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RECORD_SELECTION_TEXT {
            get {
                return ((string)(this["RECORD_SELECTION_TEXT"]));
            }
            set {
                this["RECORD_SELECTION_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int RECORD_ALL_MOD {
            get {
                return ((int)(this["RECORD_ALL_MOD"]));
            }
            set {
                this["RECORD_ALL_MOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public int RECORD_ALL_KEY {
            get {
                return ((int)(this["RECORD_ALL_KEY"]));
            }
            set {
                this["RECORD_ALL_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RECORD_ALL_TEXT {
            get {
                return ((string)(this["RECORD_ALL_TEXT"]));
            }
            set {
                this["RECORD_ALL_TEXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point IMG_0_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_0_POS"]));
            }
            set {
                this["IMG_0_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_0_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_0_RES"]));
            }
            set {
                this["IMG_0_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130, 130")]
        public global::System.Drawing.Point IMG_1_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_1_POS"]));
            }
            set {
                this["IMG_1_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_1_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_1_RES"]));
            }
            set {
                this["IMG_1_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160, 160")]
        public global::System.Drawing.Point IMG_2_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_2_POS"]));
            }
            set {
                this["IMG_2_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_2_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_2_RES"]));
            }
            set {
                this["IMG_2_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190, 190")]
        public global::System.Drawing.Point IMG_3_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_3_POS"]));
            }
            set {
                this["IMG_3_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_3_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_3_RES"]));
            }
            set {
                this["IMG_3_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 220")]
        public global::System.Drawing.Point IMG_4_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_4_POS"]));
            }
            set {
                this["IMG_4_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_4_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_4_RES"]));
            }
            set {
                this["IMG_4_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 250")]
        public global::System.Drawing.Point IMG_5_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_5_POS"]));
            }
            set {
                this["IMG_5_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_5_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_5_RES"]));
            }
            set {
                this["IMG_5_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 280")]
        public global::System.Drawing.Point IMG_6_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_6_POS"]));
            }
            set {
                this["IMG_6_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_6_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_6_RES"]));
            }
            set {
                this["IMG_6_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("310, 310")]
        public global::System.Drawing.Point IMG_7_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_7_POS"]));
            }
            set {
                this["IMG_7_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280, 188")]
        public global::System.Drawing.Size IMG_7_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_7_RES"]));
            }
            set {
                this["IMG_7_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("340, 340")]
        public global::System.Drawing.Point IMG_8_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_8_POS"]));
            }
            set {
                this["IMG_8_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 188")]
        public global::System.Drawing.Size IMG_8_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_8_RES"]));
            }
            set {
                this["IMG_8_RES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("370, 370")]
        public global::System.Drawing.Point IMG_9_POS {
            get {
                return ((global::System.Drawing.Point)(this["IMG_9_POS"]));
            }
            set {
                this["IMG_9_POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 188")]
        public global::System.Drawing.Size IMG_9_RES {
            get {
                return ((global::System.Drawing.Size)(this["IMG_9_RES"]));
            }
            set {
                this["IMG_9_RES"] = value;
            }
        }
    }
}
